version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - ./db_backup.sql:/docker-entrypoint-initdb.d/db_backup.sql
    networks:
      - sparknet

  spark:
    build: . 
    container_name: spark-emotion
    depends_on:
      - postgres
    networks:
      - sparknet

networks:
  sparknet:
    driver: bridge
