services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: project_data
    volumes:
      - postgres_volume_project:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres_volume_project:
    external: true